/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  tutorialSidebar: [{type: 'autogenerated', dirName: '.'}],
  methodeSidebar: [{type: 'autogenerated', dirName: 'methode'}],
  manuelSidebar : [{type: 'autogenerated', dirName: 'manuel'}],
};
module.exports = sidebars;